[package]
name = "kamn-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
kamn-core = { path = "../kamn-core" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile = "3"
